name: CI Build
on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Gradle build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - run: ./gradlew build
